language: python

python: 3.7

sudo: false

matrix:
  include:
    - python: 3.7
      env: TOX_ENV=qa
    - python: 3.5
      env: TOX_ENV=py3
    - python: 3.6
      env: TOX_ENV=py3
    - python: 3.7
      env: TOX_ENV=py3
    - python: 3.8
      env: TOX_ENV=py3
    - python: 3.9
      env: TOX_ENV=py3

before_script:
  - python -m pip install -U pip setuptools tox

script:
  - tox -e $TOX_ENV
